---
- name: zsh role
  tags:
    - zsh
  block:

  # assert
  - name: Assertions for zsh
    ansible.builtin.assert:
      that:
      - zsh_user != None

  # install
  - name: Install apt packages
    become: true
    ansible.builtin.apt:
      name: zsh
      state: present

  # make default shell
  - when: zsh_make_default == true
    name: Ensure zsh is the default shell for {{ zsh_user }}
    become: true
    ansible.builtin.user:
      name: "{{ zsh_user }}"
      shell: "/usr/bin/zsh"

  # theme files
  - when: zsh_files_copy_themes | length > 0
    block:

    # mkdir
    - name: Mkdir /home/{{ zsh_user }}/.zsh/themes
      become: true
      ansible.builtin.file:
        path: "/home/{{ zsh_user }}/.zsh/themes"
        state: directory
        mode: u=rwx,g=,o=
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
    
    # cp theme files
    - name: Copy theme files to /home/{{ zsh_user }}/.zshrc/themes
      become: true
      loop: "{{ zsh_files_copy_themes }}"
      ansible.builtin.copy:
        src: "themes/{{ item }}"
        dest: "/home/{{ zsh_user }}/.zsh/themes/"
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
        mode: u=rw,g=,o=

  # plugin files
  - when: zsh_files_copy_plugins | length > 0
    block:

    # mkdir
    - name: Mkdir /home/{{ zsh_user }}/.zsh/plugins
      become: true
      ansible.builtin.file:
        path: "/home/{{ zsh_user }}/.zsh/plugins"
        state: directory
        mode: u=rwx,g=,o=
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
    
    # cp plugin files
    - name: Copy plugin files to /home/{{ zsh_user }}/.zshrc/plugins
      become: true
      loop: "{{ zsh_files_copy_plugins }}"
      ansible.builtin.copy:
        src: "plugins/{{ item }}"
        dest: "/home/{{ zsh_user }}/.zsh/plugins/"
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
        mode: u=rw,g=,o=

  # zsh.oh-my-zsh
  - when: zsh_ohmyzsh == true
    block:

    # install git
    - name: Install git
      become: true
      ansible.builtin.apt:
        name: git # needed for oh-my-zsh
        state: present

    # check root
    - name: Check if oh-my-zsh is already installed (root)
      when: zsh_user == "root"
      become: true
      ansible.builtin.stat:
        path: /root/.oh-my-zsh
      register: __zsh_ohmyzsh_root

    # check user
    - name: Check if oh-my-zsh is already installed (user)
      when: zsh_user != "root"
      become: true
      ansible.builtin.stat:
        path: "/home/{{ zsh_user }}/.oh-my-zsh"
      register: __zsh_ohmyzsh_user

    # if oh-my-zsh does not exist
    - when: (zsh_user == "root" and not __zsh_ohmyzsh_root.stat.exists) or (zsh_user != "root" and not __zsh_ohmyzsh_user.stat.exists)
      block:

      # download
      - name: Download Oh My Zsh install skript
        become: true
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
          dest: /tmp/install_ohmyzsh.sh
          force: false
          owner: "{{ zsh_user }}"
          group: "{{ zsh_user }}"
      
      # run
      - name: Run Oh My Zsh install script
        become: true
        become_user: "{{ zsh_user }}"
        ansible.builtin.command:
          cmd: sh /tmp/install_ohmyzsh.sh --unattended

  # zsh.oh-my-zsh
  - when: zsh_ohmyzsh == false
    block:

    # check root
    - when: zsh_user == "root"
      name: Remove oh-my-zsh for user root
      become: true
      ansible.builtin.file:
        path: /root/.oh-my-zsh
        state: absent

    # check user
    - when: zsh_user != "root"
      name: Remove oh-my-zsh for user {{ zsh_user }}
      become: true
      ansible.builtin.file:
        path: "/home/{{ zsh_user }}/.oh-my-zsh"
        state: absent

  # zsh_config_zshrc
  - when: zsh_config_zshrc != None
    block:

    # user
    - name: Copy {{ zsh_config_zshrc }} to /home/{{ zsh_user }}/.zshrc
      when: zsh_user != "root"
      become: true
      ansible.builtin.copy:
        src: "{{ zsh_config_zshrc }}"
        dest: "/home/{{ zsh_user }}/.zshrc"
        owner: "{{ zsh_user }}"
        group: "{{ zsh_user }}"
        mode: u=rw,g=,o=
    
    # root
    - name: Copy {{ zsh_config_zshrc }} to /root/.zshrc
      when: zsh_user == "root"
      become: true
      ansible.builtin.copy:
        src: "{{ zsh_config_zshrc }}"
        dest: /root/.zshrc
        owner: root
        group: root
        mode: u=rw,g=,o=

  # apt install
  - when: zsh_apt_install | length > 0
    name: Apt install {{ zsh_apt_install  }}
    become: true
    ansible.builtin.apt:
      name: "{{ zsh_apt_install }}"
      state: present

  # apt remove
  - when: zsh_apt_remove | length > 0
    name: Apt remove {{ zsh_apt_remove }}
    become: true
    ansible.builtin.apt:
      name: "{{ zsh_apt_remove }}"
      state: absent